// <auto-generated/>
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WebForms.vNextinator")]
[assembly: AssemblyDescriptionAttribute("The future of WebForms is here!!")]
[assembly: GuidAttribute("1aa18ad4-ed25-4220-b504-e62104855800")]
[assembly: AssemblyProductAttribute("WebForms.vNextinator")]
[assembly: AssemblyVersionAttribute("0.4.1")]
[assembly: AssemblyFileVersionAttribute("0.4.1")]
[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.1";
    }
}
