// <auto-generated/>
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WebForms.vNextinator")]
[assembly: AssemblyDescriptionAttribute("The future of WebForms is here!!")]
[assembly: GuidAttribute("71d02e20-938e-415a-ae0c-7bf5c57299dd")]
[assembly: AssemblyProductAttribute("WebForms.vNextinator")]
[assembly: AssemblyVersionAttribute("0.4.4.0")]
[assembly: AssemblyFileVersionAttribute("0.4.4.0")]
[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.4.0";
        internal const string InformationalVersion = "0.4.4.0";
    }
}
